services:

    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
            WORPRESS_DEBUG: 1
            WORDPRESS_DEBUG_LOG: 1
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress:/var/www/html
            - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./config/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini

    db:
        image: mysql:8.4
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql

volumes:
    wordpress:
    db:
